/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Dracula_game_Dungeon_story.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Dracula_game_Dungeon_story: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Dracula_game_Dungeon_story()
	{
		this.StartPassage = "Entering the Dungeons (Opening cut scene)";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Entering the Dungeons (Opening cut scene)

	void passage1_Init()
	{
		this.Passages[@"Entering the Dungeons (Opening cut scene)"] = new StoryPassage(@"Entering the Dungeons (Opening cut scene)", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("On arrival to draculas castle, Alucard sees flames and a military presence surrounding the entrance to the castle, he needs to know whats going on so he sneaks into the dungeons through a old secret passage.");
		yield return lineBreak();
		yield return link("Dungeon - Entrance", "Dungeon - Entrance", null);
		yield break;
	}


	// .............
	// #2: Dungeon - Entrance

	void passage2_Init()
	{
		this.Passages[@"Dungeon - Entrance"] = new StoryPassage(@"Dungeon - Entrance", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("The entrance of the dungeon is dark being dimly lit by blue flamed torches, on entering Alucard can hear groaning, dripping/running water and can see dead bodies and skeletons all around. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard: \"Not how i remember it but i made it inside, now i need to figure out whats going on around here.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("...: \"help\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard: \"I better go see who needs help.\"");
		yield return lineBreak();
		yield return link("Dungeon - Hallway 1", "Dungeon - Hallway 1", null);
		yield break;
	}


	// .............
	// #3: Dungeon - Hallway 1

	void passage3_Init()
	{
		this.Passages[@"Dungeon - Hallway 1"] = new StoryPassage(@"Dungeon - Hallway 1", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("while progressing through the first hallway of the dungeon Alucard sees jail cells with corpses of died vampires inside, while looking around he hears the groaning get louder and another scream for help.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("...:\"heelllpp\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Sword room", "Dungeon - Sword room", null);
		yield break;
	}


	// .............
	// #4: Dungeon - Sword room

	void passage4_Init()
	{
		this.Passages[@"Dungeon - Sword room"] = new StoryPassage(@"Dungeon - Sword room", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Alucard sees a blood drain vampire trying to pull out a sword he seems to recognise. the vampire hears you approach and attacks you (combat tutorial), after dispatching the vampire you move towards the sword.");
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("“Reinfeld? What are you doing down in this pit, shouldn’t you be with my farther and could you explain why part of the castle is in flames right now.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Renfield: ");
		yield return lineBreak();
		yield return text("“SOLDIERS INVADED THE CASTLE!!!”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("“WHAT? I mean could you calm down and explain it properly before you attract more trouble.”");
		yield return lineBreak();
		yield return text(" ");
		yield return lineBreak();
		yield return text("Renfield:");
		yield return lineBreak();
		yield return text("“Ahem, sorry I just thought being direct would help you understand quicker. The situation is pretty bad, there using Dracula to control the vampires whilst researchers study them. They blackmailed him by capturing his wives first and then locked me down here so I couldn’t help your farther fight back, now...CAN YOU PULL ME OUT OF THIS STONE.” ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard pulls reinfeild out the stone and proceeds to the next area of the dungeon (weapon aquired).");
		yield return lineBreak();
		yield return link("Dungeon - Hallway 2", "Dungeon - Hallway 2", null);
		yield break;
	}


	// .............
	// #5: Dungeon - Hallway 2

	void passage5_Init()
	{
		this.Passages[@"Dungeon - Hallway 2"] = new StoryPassage(@"Dungeon - Hallway 2", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("As you move towards the next part of the dungeon you hear a screeching noise.");
		yield return lineBreak();
		yield return text("\"blooooddd\"");
		yield return lineBreak();
		yield return text("As you get closer to the noise you find more blood drained vampires you need to fight (tutorial for the sword).");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("“I told you to be quiet, let’s deal with this problem quick” ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Reinfeld: ");
		yield return lineBreak();
		yield return text("“Of course it’s my fault, ahhhh.” ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You engage with the enemies and fight them off. after defeating them you overhear some people talking, possibly the soilders?");
		yield return lineBreak();
		yield return link("Dungeon - Hallway 3", "Dungeon - Hallway 3", null);
		yield break;
	}


	// .............
	// #6: Dungeon - Hallway 3

	void passage6_Init()
	{
		this.Passages[@"Dungeon - Hallway 3"] = new StoryPassage(@"Dungeon - Hallway 3", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Alucard sees that they are soldiers and hides to listen to the conversation to try gain information.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Soldier 1:");
		yield return lineBreak();
		yield return text(" “God, why am I down in this stupid dungeon, I should be helping take over the rest of the castle.”");
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return text("Soldier 2:");
		yield return lineBreak();
		yield return text("“You? You must be joking, you were terrified when we were capturing Draculas castle, looked to me like you where gonna wet yourself, just pay attention we need to deal with any problems down here.");
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return text("You can engage in combat:");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Second Arena", "Dungeon - Second Arena", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return text("or take a secret passage you see in one of the cells:");
		yield return lineBreak();
		yield return link("Dungeon - secret passage", "Dungeon - secret passage", null);
		yield break;
	}


	// .............
	// #7: Dungeon - Second Arena

	void passage7_Init()
	{
		this.Passages[@"Dungeon - Second Arena"] = new StoryPassage(@"Dungeon - Second Arena", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Alucard chooses to engage with the soilders:");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Soldier 1:");
		yield return lineBreak();
		yield return text("“Whatever, huh? Whos there?”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("“Your the ones that invaded my home, your end shall be swift”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Soldier 2:");
		yield return lineBreak();
		yield return text("“What are you doing? FIRE!!!.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Hallway 4", "Dungeon - Hallway 4", null);
		yield break;
	}


	// .............
	// #8: Dungeon - secret passage

	void passage8_Init()
	{
		this.Passages[@"Dungeon - secret passage"] = new StoryPassage(@"Dungeon - secret passage", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Alucard chooses to take the secret passage:");
		yield return lineBreak();
		yield return text("Reinfield:");
		yield return lineBreak();
		yield return text("\"That was useful, it allowed us to skip passed those soldiers\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("\"Even though i wanted to deal with them, guess this easier\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Reinfield:");
		yield return lineBreak();
		yield return text("\"Is that some looot, that'll be useful\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("gained some potions");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Hallway 4", "Dungeon - Hallway 4", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #9: Dungeon - Hallway 4

	void passage9_Init()
	{
		this.Passages[@"Dungeon - Hallway 4"] = new StoryPassage(@"Dungeon - Hallway 4", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("A long hallway with multiple directions");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Third Arena", "Dungeon - Third Arena", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Hidden room", "Dungeon - Hidden room", null);
		yield break;
	}


	// .............
	// #10: Dungeon - Third Arena

	void passage10_Init()
	{
		this.Passages[@"Dungeon - Third Arena"] = new StoryPassage(@"Dungeon - Third Arena", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Alucard fights through more enemies");
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("\"lets gather what we can and turn back\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Reinfeild:");
		yield return lineBreak();
		yield return text("\"good idea, lets do that.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Dead end", "Dungeon - Dead end", null);
		yield break;
	}


	// .............
	// #11: Dungeon - Hidden room

	void passage11_Init()
	{
		this.Passages[@"Dungeon - Hidden room"] = new StoryPassage(@"Dungeon - Hidden room", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Alucard finds more potions");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("\"that'll come in handy\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Forth arena", "Dungeon - Forth arena", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #12: Dungeon - Dead end

	void passage12_Init()
	{
		this.Passages[@"Dungeon - Dead end"] = new StoryPassage(@"Dungeon - Dead end", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Alucard grabs loot for beating the enemies in this area.");
		yield break;
	}


	// .............
	// #13: Dungeon - Forth arena

	void passage13_Init()
	{
		this.Passages[@"Dungeon - Forth arena"] = new StoryPassage(@"Dungeon - Forth arena", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("\"why are the weak vampires helping the soldiers?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Reinfield:");
		yield return lineBreak();
		yield return text("\"there using mind control, werent you listening earlier???\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("\"oh well get we better take them out should nearly be out the dungeon at this point.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Hallway 5", "Dungeon - Hallway 5", null);
		yield break;
	}


	// .............
	// #14: Dungeon - Hallway 5

	void passage14_Init()
	{
		this.Passages[@"Dungeon - Hallway 5"] = new StoryPassage(@"Dungeon - Hallway 5", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("You make your way to the last room and see a figure standing there.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Boss Arena", "Dungeon - Boss Arena", null);
		yield break;
	}


	// .............
	// #15: Dungeon - Boss Arena

	void passage15_Init()
	{
		this.Passages[@"Dungeon - Boss Arena"] = new StoryPassage(@"Dungeon - Boss Arena", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("if you engage the enemies in the second arena:");
		yield return lineBreak();
		yield return text("Higher up Soldier 1:");
		yield return lineBreak();
		yield return text("“ You must be the one that ran away from home? guess ill deal with you for taking out my men.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("“I did not run away, I was on a vacation of sorts, ugh that doesn’t matter be ready to be like your men.” ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("if you didnt engage the enemies in the second arena:");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Higher up Soldier 1:");
		yield return lineBreak();
		yield return text("“ You must be the one that ran away from home? guess ill deal with you before you become troublesome for my boss.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Alucard:");
		yield return lineBreak();
		yield return text("“I did not run away, I was on a vacation of sorts, ugh like you could deal with me.”");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("After defeating the boss you gain his helmet (item for trading) and are able to proceed into the castle.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Dungeon - Exit", "Dungeon - Exit", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #16: Dungeon - Exit

	void passage16_Init()
	{
		this.Passages[@"Dungeon - Exit"] = new StoryPassage(@"Dungeon - Exit", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}