/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Supa_Epic_Dracula_Game_1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Supa_Epic_Dracula_Game_1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Supa_Epic_Dracula_Game_1()
	{
		this.StartPassage = "Opening cut scene";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Opening cut scene

	void passage1_Init()
	{
		this.Passages[@"Opening cut scene"] = new StoryPassage(@"Opening cut scene", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Images of Alucard approaching the castle, he sees a military presence and chooses to enter into the dungeons to sneak in ");
		yield return lineBreak();
		yield return link("Arrives in first room", "Arrives in first room", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: hallway1

	void passage2_Init()
	{
		this.Passages[@"hallway1"] = new StoryPassage(@"hallway1", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Jail cells with dead bodies or living creatures or people (currency in them you can pick up?) ");
		yield return lineBreak();
		yield return text("Hear's another voice line from sword");
		yield return lineBreak();
		yield return text("Hear some screaming or groaning ");
		yield return lineBreak();
		yield return text("Rotting bodies ");
		yield return lineBreak();
		yield return link("sword room", "sword room", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: Arrives in first room

	void passage3_Init()
	{
		this.Passages[@"Arrives in first room"] = new StoryPassage(@"Arrives in first room", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Alucard makes a comment on the occupation of the castle and wonders where his family is");
		yield return lineBreak();
		yield return text("Room is dark but dimly lit by torches");
		yield return lineBreak();
		yield return text("Pools of blood, chains, dripping water (sound), dead body or skeleton ");
		yield return lineBreak();
		yield return text("He hears a voice calling to him");
		yield return lineBreak();
		yield return link("hallway1", "hallway1", null);
		yield break;
	}


	// .............
	// #4: sword room

	void passage4_Init()
	{
		this.Passages[@"sword room"] = new StoryPassage(@"sword room", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Sword talks to player directly: ");
		using (Group("em", true)) {
			yield return text("Insert dialogue");
		}
		yield return text(" ");
		yield return lineBreak();
		yield return text("Sword is stuck in something (ground?)");
		yield return lineBreak();
		yield return text("Alucard pulls out sword ");
		yield return lineBreak();
		yield return text("Breakable barrels and crates blocking forward movement (use the sword, given a quick tutorial on how to swing the sword) ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("hallway2", "hallway2", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #5: hallway2

	void passage5_Init()
	{
		this.Passages[@"hallway2"] = new StoryPassage(@"hallway2", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Sword tells you there's something up ahead(");
		using (Group("em", true)) {
			yield return text("insert dialogue");
		}
		yield return text(")");
		yield return lineBreak();
		yield return text("Similar scenery and atmopshere to hallway 1 ");
		yield return lineBreak();
		yield return link("arena1", "arena1", null);
		yield break;
	}


	// .............
	// #6: arena1

	void passage6_Init()
	{
		this.Passages[@"arena1"] = new StoryPassage(@"arena1", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Sword and Alucard have discussion about the creatures looking different or agressive (mind controlled vampiric creatures)");
		yield return lineBreak();
		yield return text("engage in combat (bat pun?)");
		yield return lineBreak();
		yield return text("Conversation after fight about what could be going on in the castle (sword has knowledge or not?)");
		yield return lineBreak();
		yield return text("Fight should be pretty easy and have the enemy/enemies move around the large room with platforms");
		yield return lineBreak();
		yield return link("hallway3", "hallway3", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #7: hallway3

	void passage7_Init()
	{
		this.Passages[@"hallway3"] = new StoryPassage(@"hallway3", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("More cells with loot or monsters etc. ");
		yield return lineBreak();
		yield return text("Choice of directions");
		yield return lineBreak();
		yield return text("More conversation with sword (");
		using (Group("em", true)) {
			yield return text("insert dialogue");
		}
		yield return text(") ");
		yield return lineBreak();
		yield return text("Empty cells have extra rewards in them for beating first arena ");
		yield return lineBreak();
		yield return link("secret passage", "secret passage", null);
		yield return lineBreak();
		yield return link("second arena", "second arena", null);
		yield break;
	}


	// .............
	// #8: secret passage

	void passage8_Init()
	{
		this.Passages[@"secret passage"] = new StoryPassage(@"secret passage", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Player can find this within a cell on the far right but must not open all other cells which are full of enemies ");
		yield return lineBreak();
		yield return text("Leads into hallway4");
		yield return lineBreak();
		yield return link("hallway4", "hallway4", null);
		yield break;
	}


	// .............
	// #9: second arena

	void passage9_Init()
	{
		this.Passages[@"second arena"] = new StoryPassage(@"second arena", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Fight a stronger enemy/ stronger enemies ");
		yield return lineBreak();
		yield return link("hallway4", "hallway4", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #10: hallway4

	void passage10_Init()
	{
		this.Passages[@"hallway4"] = new StoryPassage(@"hallway4", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Longer hallway with multiple directions");
		yield return lineBreak();
		yield return link("third arena", "third arena", null);
		yield return lineBreak();
		yield return link("hidden area room", "hidden area room", null);
		yield break;
	}


	// .............
	// #11: third arena

	void passage11_Init()
	{
		this.Passages[@"third arena"] = new StoryPassage(@"third arena", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return link("dead end", "dead end", null);
		yield break;
	}


	// .............
	// #12: hidden area room

	void passage12_Init()
	{
		this.Passages[@"hidden area room"] = new StoryPassage(@"hidden area room", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return link("fourth arena", "fourth arena", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #13: dead end

	void passage13_Init()
	{
		this.Passages[@"dead end"] = new StoryPassage(@"dead end", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Loot for beating the arena in here");
		yield break;
	}


	// .............
	// #14: fourth arena

	void passage14_Init()
	{
		this.Passages[@"fourth arena"] = new StoryPassage(@"fourth arena", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return link("hallway5", "hallway5", null);
		yield break;
	}


	// .............
	// #15: hallway5

	void passage15_Init()
	{
		this.Passages[@"hallway5"] = new StoryPassage(@"hallway5", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return link("boss arena", "boss arena", null);
		yield break;
	}


	// .............
	// #16: boss arena

	void passage16_Init()
	{
		this.Passages[@"boss arena"] = new StoryPassage(@"boss arena", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return link("exit stairs", "exit stairs", null);
		yield break;
	}


	// .............
	// #17: exit stairs

	void passage17_Init()
	{
		this.Passages[@"exit stairs"] = new StoryPassage(@"exit stairs", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}